account/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from . import views
from .views import profile_list,profile_detail


app_name = "account"
urlpatterns = [
    # url-адреса входа и выхода
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    ## url-адреса смены пароля
    # path('password-change/', auth_views.PasswordChangeView.as_view(),
    #     name='password_change'),
    # path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
    #     name='password_change_done'),
    ## url - сброса пароля
    # path('password-reset/', auth_views.PasswordResetView.as_view(),
    #     name='password_reset'),
    # path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
    #     name='password_reset_confirm'),
    # path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
    #     name='password_reset_complete'),
    path('', include('django.contrib.auth.urls')),  # url для встроенных вьюшек аутентификаций
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('profiles/', profile_list, name='profile_list'),
    path('profiles/<str:username>/', profile_detail, name='profile_detail'),
    path('token_login/', views.token_login, name='token_login'),


]

detectionsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace="account")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <span class="logo">ПРОЕКТ</span>
    {% if request.user.is_authenticated %}
    <ul class="menu">
        <li {% if section == 'dashboard' %}class="selected"{% endif %}>
        <a href="{% url 'account:dashboard' %}">My dashboard</a>
        </li>
        <li {% if section == 'ímages' %}class="selected"{% endif %}>
        <a href="#">Images</a>
        </li>
        <li {% if section == "people" %}class="selected"{% endif %}>
        <a href="#">People</a>
        </li>
    </ul>
    {% endif %}
    <span class="user">
      {% if request.user.is_authenticated %}
        Hello {{ request.user.first_name|default:request.user.username }},
        <form action="{% url 'account:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Log out</button>
        </form>
        {% else %}
        <a href="{% url 'account:login' %}">Log-in</a>
        {% endif %}
    </span>
</div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags }}">
        {{ message|safe }}
        <a href="#" class="close">x</a>
    </li>
    {% endfor %}
</ul>
{% endif %}
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>